# ==============================================================================
#                      ZAPPY SERVER CONFIGURATION FILE
# ==============================================================================

# ------------------------------------------------------------------------------
# Game Server Block
# ------------------------------------------------------------------------------

game {
    host                0.0.0.0;
    port                4242;
    width               10;
    height              10;
    teams               TeamRed TeamBlue;
    clients_per_team    4;
    time                100;
}

# ------------------------------------------------------------------------------
# Admin Server Block
# ------------------------------------------------------------------------------

admin {
    host                0.0.0.0;
    port                4243;
}

# ------------------------------------------------------------------------------
# Graphic Client (GUI) Server Block
# ------------------------------------------------------------------------------

gui {
    host                0.0.0.0;
    port                4244;
}
