
game {
    host                0.0.0.0;
    port                4242;
    width               10;
    height              10;
    teams               TeamRed TeamBlue;
    time                1;
}

admin {
    host                0.0.0.0;
    port                4243;
    certificate         certs/server.crt;
    private_key         certs/server.key;
    password            zappy-admin;
}

gui {
    host                0.0.0.0;
    port                4244;
}
